version: '3.8'

services:
  db:
    image: postgres:16
    container_name: nn-homework-db
    environment:
      POSTGRES_DB: homework
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  app:
    build: .
    container_name: nn-homework-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/homework
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"

      SPRING_BATCH_JDBC_INITIALIZE_SCHEMA: never
      SPRING_BATCH_JOB_ENABLED: "false"

    depends_on:
      - db
volumes:
  postgres_data: